@startuml
skinparam maxMessageSize 100
skinparam packageStyle rectangle
title Регулятор
set namespaceSeparator none
class DExS {
.. Назначение ..
Регулирование тока возбуждения
в соответствии с заложенной программой
.. Платы ..
+ DExS.CRB.FLAT : Объединительная (кросс-плата)
+ DExS.M4CPU : Процессорная
+ DExS.PWR2 : Синхронизация
+ DExS.DIO : Дискретные входы/выходы
+ AVS.BIT : Усилитель управляющих сигналов тиристоров
+ КП256 : Ключ резервной копии параметров
} 

class DExS.CRB.FLAT{
.. Назначение ..
Объединение основных плат
.. Особенности ..
Высота и тип зависит от кол-ва плат AVS.BIT
+DExS.CRB.FLAT rev1.0 : одна плата AVS.BIT
    PN:
    1С:
+DExS.CRB.FLAT rev3.0: две платы AVS.BIT
    PN:
    1С:
}

class DExS.M4CPU{
    PN:
    1С:
.. Входы ..
+ Измерение тока ротора : -120..0..+120 мВ 
- Измерение напряжения ротора : -600..0..+600 В 
+ Измерение напряжения статора (одна фаза): 
    0..120 VAC  диапазон 100В
    0..450 VAC  диапазон 380В
    Не обязательный датчик т.к. используется DExS.CPU.VTEG
+ Измерение тока статора (одна фаза): 0..30АС 50Гц
   Не обязательный датчик т.к. используется DExS.CPU.VTEG
+ 3-х фазный датчик тока выпрямителя : 0..15 АС
   Подключается к стандартным тр-рам тока ХХХ/5А
   Требуется общая точка тр-ров
+ Датчик скольжения: +/- 15В
   контроль проводимости разрядной цепи
== Интерфейсы ==
+ RS485 для связи с iCM
+ USB
+ KП256 резервная копия уставок
.. Опции ..
* DExS.CPU.VTEG : Основная
+DExS.CPU.RS485 : Дополнительная
.. Особенности ..
+ Номинал микросхемы датчика тока статора, должен быть
   2-х, 3-х кратный для более точного измерения тока.
- Делитель датчика напряжения ротора должен учитывать
   3-х кратное превышение напряжения возбуждения генератора
+ Для напряжения статора 380В устанавливается перемычка
 - Общую точку тр-ров тока заземлить!
+ Требуется калибровка датчиков
} 

class AVS.BIT {
    PN:
    1С:
.. Назначение ..
6 выходов упр-я тиристорами 
высокочастотная накачка 200КГц
.. Особенности ..
SELECT запаивать в зависимости
от положения в DExS.CRB.FLAT.
По умолчанию вставляется в верхний ряд
} 

class DExS.DIO {
    PN:
    1С:
.. Назначение ..
16 дискретных входов 24VDC 
16 дискретных выходов 0.3А 24VDC
.. Особенности ..
Отдельное питание 24VDC входов и выходов
} 

class DExS.PWR2{
    PN:
    1С:
.. Назначение ..
  Синхронизация
  Контроль изоляции: 0..2000 КОм (шаг 63Ом)
  Преобразование 24DVC в 5VDC питания плат
.. Особенности ..
- Установить DIP-переключатель в зависимости
   от напряжения синхронизации
- Минимальное напряжение
   синхронизации ХХ VAC
- При нулевой схеме выпрямителя,
   на N1 завести НОЛЬ тр-ра
   или доп обмотки статора
+ Требуется калибровка
} 

class DExS.CPU.VTEG {
    PN:
    1С:
.. Назначение ..
Основное измерительное средство
систем возбуждения генераторов
Измерение:
~3-х фазного линейного напряжения сети,
~3-х фазного линейного напряжения генератора,
~1-ф тока генератора
.. Параметры цепей ..
+ Напряжение: выбирается перемычкой
    0..120 VAC  диапазон 100В
    0..450 VAC  диапазон 380В (с перемычкой)
+ Ток:
    0..30АС 50Гц
    Номинал микросхемы датчика тока статора,
    должен быть 2-х, 3-х кратный для более
    точного измерения тока.
} 

class DExS.CPU.RS485 {
    PN:
    1С:
.. Назначение ..
Дополнительный
интерфейс RS485
}

class КП256 {
    PN:
    1С:
.. Назначение ..
Ключ резервной
копии уставок
}

DExS <-- DExS.CRB.FLAT
DExS.CRB.FLAT <-- DExS.PWR2
DExS.CRB.FLAT <-- DExS.M4CPU
DExS.CRB.FLAT <-- DExS.DIO
DExS.CRB.FLAT <-- AVS.BIT
DExS.M4CPU <-- DExS.CPU.RS485
DExS.M4CPU <-- DExS.CPU.VTEG
DExS.M4CPU <-- КП256

@enduml
