@startuml

skinparam maxMessageSize 100
skinparam packageStyle rectangle
title Состав электроники [[http://plantuml.com{Optional tooltip} This label is printed]]
set namespaceSeparator none

class DExS {
.. Назначение ..
Регулирование тока возбуждения
в соответствии с заложенной программой
.. Платы ..
+ DExS.CRB.FLAT : Объединительная (кросс-плата)
+ DExS.M4CPU : Процессорная
+ DExS.PWR2 : Синхронизация
+ DExS.DIO : Дискретные входы/выходы
+ AVS.BIT : Усилитель управляющих сигналов тиристоров
} 

class DExS.CRB.FLAT{
.. Назначение ..
Объединение основных плат
.. Особенности ..
Высота и тип зависит от кол-ва плат AVS.BIT
DExS.CRB.FLAT rev1.0 : одна плата AVS.BIT
DExS.CRB.FLAT rev3.0: две платы AVS.BIT
}

class DExS.M4CPU{
.. Назначение..
+ Измерение тока ротора : -120..0..+120 мВ 
- Измерение напряжения ротора : -600..0..+600 В 
+ Измерение напряжения статора (одна фаза): 
    0..120 VAC  диапазон 100В
    0..450 VAC  диапазон 380В
    Не обязательный датчик т.к. используется DExS.CPU.VTEG
+ Измерение тока статора (одна фаза): 0..30АС 50Гц
   Не обязательный датчик т.к. используется DExS.CPU.VTEG
+ 3-х фазный датчик тока выпрямителя : 0..15 АС
   Подключается к стандартным тр-рам тока ХХХ/5А
   Требуется общая точка тр-ров
+ Датчик скольжения: +/- 15В
   контроль проводимости разрядной цепи
.. Опции ..
* DExS.CPU.VTEG : Основная
+DExS.CPU.RS485 : Дополнительная
.. Особенности ..
+ Номинал микросхемы датчика тока статора, должен быть
   2-х, 3-х кратный для более точного измерения тока.
- Делитель датчика напряжения ротора должен учитывать
   3-х кратное превышение напряжения возбуждения генератора
+ Для напряжения статора 380В устанавливается перемычка
 - Общую точку тр-ров тока заземлить!
+ Требуется калибровка датчиков
} 

class AVS.BIT {
.. Назначение ..
6 выходов упр-я тиристорами 
высокочастотная накачка 200КГц
.. Особенности ..
SELECT запаивать в зависимости
от положения в DExS.CRB.FLAT.
По умолчанию вставляется в верхний ряд
} 

class DExS.DIO {
.. Назначение ..
16 дискретных входов 24VDC 
16 дискретных выходов 0.3А 24VDC
.. Особенности ..
Отдельное питание 24VDC входов и выходов
} 

class DExS.PWR2{
.. Назначение ..
  Синхронизация
  Контроль изоляции: 0..2000 КОм (шаг 63Ом)
  Преобразование 24DVC в 5VDC питания плат
.. Особенности ..
- Установить DIP-переключатель в зависимости от напряжения синхронизации
- Минимальное напряжение синхронизации ХХ VAC
- При нулевой схеме выпрямителя,
   на N1 завести НОЛЬ тр-ра или доп обмотки статора
+ Требуется калибровка
} 

class DExS.CPU.VTEG {
.. Назначение ..
Измерение:
3-х фазного линейного напряжения сети,
3-х фазного линейного напряжения генератора,
1-ф тока генератора
..
Изображение:
} 

class DExS.CPU.RS485 {
.. Назначение ..
Дополнительный интерфейс RS485
..
Изображение:
} 

DExS <-- DExS.CRB.FLAT
DExS.CRB.FLAT <-- DExS.PWR2
DExS.CRB.FLAT <-- DExS.M4CPU
DExS.CRB.FLAT <-- DExS.DIO
DExS.CRB.FLAT <-- AVS.BIT
DExS.M4CPU <-- DExS.CPU.RS485
DExS.M4CPU <-- DExS.CPU.VTEG
@enduml


