iCM




@startuml
skinparam maxMessageSize 100
skinparam packageStyle rectangle
set namespaceSeparator none

class iCM {
PN:
1С:
.. Назначение ..
+ Контроль и арбитраж регуляторов
+ Связь с АСУ ТП
+ Передача релейных сигналов в КИПиА
+ Вывод сигналов КИПиА по 0..20мА интерфейсам
+ Ввод сигналов КИПиА по 0..20мА интерфейсам
.. Платы ..
+ iCM.CPU : Процессорная
+ iCM.AIO : Входы/выходы
} 

class iCM.CPU{
    PN:
    1С:
== Интерфейсы ==
+ 4шт RS485 для связи с iCM
+ Ethernet
.. Опции ..
* iCM.AIO : Основная
+ iCM.AIOv2 : Дополнительная
.. Особенности ..
Ethernet паять при необходимости
} 

class iCM.AIO {
    PN:
    1С:
.. Назначение ..
.. Аналоговые входы/выходы .. 
+ 2шт входы 0..20мА
+ 3шт выходы 0..20мА
.. Дискретные входы/выходы ..
+ 12шт входы 24VDC
+ 8шт выходы 24VDC 300mA
} 

iCM <-- iCM.CPU
iCM.CPU <-- iCM.AIO
@enduml
